implement and test ThingIFAPI.aggregate.
KiiPlatform/IoTCloud-iOSSDK pull request #375
Opened 2017-03-15 08:50 UTC by naoki-akimoto

ThingIFAPI.aggregateを実装しスモールテストを追加しました。レビューをお願いします。
ラージテストに関してはそもそもSwift3対応がされていないようなので別で行います。

2017-03-15 09:07 UTC, yongpingchen requested changes

2017-03-15 09:07 UTC, yongpingchen commented on ThingIFSDK/ThingIFSDK/ThingIFAPI.swift
> +                            let aggregation = aggregations[0]
there is only 1 aggregation. What about just 
```
let aggregation = (result["aggregations"]  as! [[String: Any]])[0]
```

2017-03-15 09:07 UTC, yongpingchen commented on ThingIFSDK/ThingIFSDK/ThingIFAPI.swift
> +                                let createdAt = Date(timeIntervalSince1970: object["_created"] as! TimeInterval)
It is better to implement `FromJsonObject` protocol for `HistoryState`

2017-03-15 09:18 UTC, dairyo requested changes
@naoki-akimoto 確認お願いします。

2017-03-15 09:18 UTC, dairyo commented on ThingIFSDK/ThingIFSDK/AggregatedResult.swift
> +    public let value: AggregatedValueType?
@naoki-akimoto オプショナルに変更したのはなぜですか？

aggregateされた結果が返ってこないことがあり得る？

2017-03-15 09:18 UTC, dairyo commented on ThingIFSDK/ThingIFSDK/ThingIFAPI.swift
> +                        ]
@naoki-akimoto `Aggreation`にも`ToJsonObject`をadoptさせましょう。

2017-03-15 09:18 UTC, shinsuke-nara commented on ThingIFSDK/ThingIFSDK/ThingIFAPI.swift
> +                    "clause": clause,
@naoki-akimoto queryを作る処理は、`GroupedHistoryStateQuery`に`ToJsonObject`を adoptさせて、そこで行うことってできますか？

2017-03-15 09:18 UTC, shinsuke-nara commented on ThingIFSDK/ThingIFSDK/ThingIFAPI.swift
> +                if response != nil {
`if let response = response {`とすれば、`response?`は`response`で行けるようになります。

2017-03-15 09:18 UTC, shinsuke-nara commented on ThingIFSDK/ThingIFSDK/ThingIFAPI.swift
> +                    queryResults.forEach { result in
これだけ長いと

`for result in queryResults {` の方がわかりやすいかなぁ。

`map`を使うなら長いのもある程度アリかなぁとも思う。

2017-03-15 09:18 UTC, shinsuke-nara commented on ThingIFSDK/ThingIFSDK/ThingIFAPI.swift
> +                            }
@naoki-akimoto 仕様上、`range`と`aggregations`は必ず来る想定ですか？もしそうならば、ここのチェックはなくしましょう。サーバを信じるスタイルで行きましょう。

2017-03-15 09:18 UTC, shinsuke-nara commented on ThingIFSDK/ThingIFSDK/ThingIFAPI.swift
> +                            if aggregation["object"] != nil {
@naoki-akimoto 'value'と'object'についても仕様としてある想定ならチェックはしないで行きましょう。

2017-03-15 09:18 UTC, shinsuke-nara commented on ThingIFSDK/ThingIFSDK/ThingIFAPI.swift
> +                                completionHandler([], nil)
@naoki-akimoto ここはそのままエラーを返さないのはなぜ？

2017-03-15 09:18 UTC, shinsuke-nara commented on ThingIFSDK/ThingIFSDKTests/ThingIFAPIAggregateTests.swift
> +            let object : HistoryState = result.aggregatedObjects[0]
XCTTest+Equatable.swiftの中に、extensionを追加して、HistoryStateをEqutableにadoptさせましょう。

2017-03-15 09:20 UTC, naoki-akimoto commented on ThingIFSDK/ThingIFSDK/AggregatedResult.swift
> +    public let value: AggregatedValueType?
仕様上あり得ます、これはyongpingさんにも確認済みでAndroid側は修正済みです。

2017-03-15 09:23 UTC, naoki-akimoto commented on ThingIFSDK/ThingIFSDK/ThingIFAPI.swift
> +                            if aggregation["object"] != nil {
こちらは入らない可能性があります。

2017-03-15 09:24 UTC, naoki-akimoto commented on ThingIFSDK/ThingIFSDK/ThingIFAPI.swift
> +                                completionHandler([], nil)
409で"STATE_HISTORY_NOT_AVAILABLE"の場合の仕様です。Android側でも同様です。

2017-03-15 09:27 UTC, shinsuke-nara commented on ThingIFSDK/ThingIFSDK/AggregatedResult.swift
> +    public let value: AggregatedValueType?
@naoki-akimoto どのような状況でaggregateされた結果が返ってこないのでしょうか。説明、またはその仕様が記述された文章を教えていただけますか？

2017-03-15 09:58 UTC, naoki-akimoto commented on ThingIFSDK/ThingIFSDK/AggregatedResult.swift
> +    public let value: AggregatedValueType?
レンジにHistoryStateが何も含まれない場合です。

2017-03-15 09:58 UTC, naoki-akimoto commented on ThingIFSDK/ThingIFSDK/AggregatedResult.swift
> +    public let value: AggregatedValueType?
https://wiki.kii.com/display/Products/Time+Series+Bucket#TimeSeriesBucket-AggregateFunctions
ここを確認してください。

2017-03-15 11:29 UTC, naoki-akimoto commented
@yongpingchen @shinsuke-nara fixed. Please confirm.

2017-03-16 03:10 UTC, yongpingchen approved these changes

2017-03-16 03:44 UTC, shinsuke-nara commented on ThingIFSDK/ThingIFSDK/ThingIFAPI.swift
> +        let requestBody : [ String : Any] = ["query" : queryBody ]
変更しなくても大丈夫ですが、

```swift
query.makeJsonObject + ["aggregation" : [aggregation.makeJsonObject()]]
```

とかけます。

2017-03-16 03:51 UTC, dairyo approved these changes

2017-03-16 03:51 UTC, shinsuke-nara commented on ThingIFSDK/ThingIFSDK/ThingIFAPI.swift
> +            self.defaultHeader + ["Content-Type" : "application/vnd.kii.TraitStateQueryRequest+json"],
@naoki-akimoto Content-Typeの中身はUtils/Mediatype.swiftでenumで定義しているので、そこに移してください。

2017-03-16 03:51 UTC, shinsuke-nara commented on ThingIFSDK/ThingIFSDKTests/XCTest+Equatable.swift
> +            NSDictionary(dictionary: left.state) == NSDictionary(dictionary: right.state) &&
書き直さなくても結構ですが、`as NSDictionary`で変換できます。castの方が短くかけるので便利ですよ。

2017-03-16 03:54 UTC, shinsuke-nara commented
@naoki-akimoto Content-Typeの値をMediaType.swiftで定義するようにしてください。

他はLGTM.

修正後、マージしていただいて結構です。

2017-03-16 04:52 UTC, merged