implement and test ThingIFAPI.query(HistoryStateQuery).
KiiPlatform/IoTCloud-iOSSDK pull request #412
Opened 2017-03-28 09:41 UTC by naoki-akimoto

ThingIFAPI.query(HistoryStateQuery)の実装を行いテストを追加しました。レビューをお願いします。

HisotryStateQuery.clauseがAndroid側では省略不可となっていました。奈良さんと相談の上Android側に合わせて省略不可へ修正しました。

2017-03-28 09:55 UTC, dairyo requested changes
@naoki-akimoto
Please confirm.

2017-03-28 09:55 UTC, shinsuke-nara commented on ThingIFSDK/ThingIFSDK/HistoryStatesQuery.swift
> +        if self.firmwareVersion != nil {
`!= nil`のチェックは不要です。nilを代入しても何も起こらないので。

最初に

```swift
var json: [String : Any] = ["query" : ["clause" : (self.clause as! ToJSonObject).makeJsonObject()]
```

で`Dictionary`を作って、あとは代入していくだけでOKです。

2017-03-28 09:55 UTC, shinsuke-nara commented on ThingIFSDK/ThingIFSDK/ThingIFAPI.swift
>      // MARK: Qeury state history.
この`MARK`も向こうに移動させておいてください。

2017-03-28 09:55 UTC, shinsuke-nara commented on ThingIFSDK/ThingIFSDKTests/ThingIFAPIQueryUngroupedTests.swift
> +            XCTAssertEqual(historyState, result)
配列の`XCTAssertEqual`を使ってください。nilチェックも数のチェックも不要になります。

2017-03-28 09:55 UTC, shinsuke-nara commented on ThingIFSDK/ThingIFSDKTests/ThingIFAPIQueryUngroupedTests.swift
> +                String.init(data: request.httpBody!, encoding: .utf8)
Stringでのチェックよりはdictionaryでのチェックの方がいい気がします。
Stringdだと順番も完全一致じゃないと失敗するので何かと面倒なことが起こりそう。

2017-03-28 09:55 UTC, shinsuke-nara commented on ThingIFSDK/ThingIFSDKTests/ThingIFAPIQueryUngroupedTests.swift
> +            XCTAssertEqual(0, results!.count)
空の配列のとチェックに変更しましょう。

2017-03-28 10:15 UTC, naoki-akimoto commented on ThingIFSDK/ThingIFSDKTests/ThingIFAPIQueryUngroupedTests.swift
> +                String.init(data: request.httpBody!, encoding: .utf8)
Aggregateを実装した際に[String, Any]の場合はXCTAssertEqualが使えないのを確認しています。
ここに関してはStringで比較する以外方法がありません。

2017-03-29 02:24 UTC, yongpingchen approved these changes

2017-03-29 02:31 UTC, shinsuke-nara commented on ThingIFSDK/ThingIFSDKTests/ThingIFAPIQueryUngroupedTests.swift
> +                String.init(data: request.httpBody!, encoding: .utf8)
@naoki-akimoto 

`as NSDictionary`でキャストすれば可能なはずです。確認してみてください。

2017-03-29 02:34 UTC, shinsuke-nara commented
@naoki-akimoto 

https://github.com/KiiPlatform/thing-if-iOSSDK/pull/412#discussion_r108580618

こちらのコメント以外、問題ありません。
確認、必要ならば修正していただければLGTM.

2017-03-29 02:34 UTC, dairyo approved these changes

2017-03-29 03:03 UTC, rizakii approved these changes

2017-03-29 03:53 UTC, merged