implement and test ThingIFAPI.query(Grouped).
KiiPlatform/IoTCloud-iOSSDK pull request #419
Opened 2017-03-29 09:54 UTC by naoki-akimoto

ThingIFAPI.query(Grouped)を実装しテストを追加しました。レビューをお願いします。

GroupedHistoryStatesQueryのmekJsonObject内でJsonの生成を完結させるため、aggregate側も修正していますので注意してください。

2017-03-29 10:17 UTC, rizakii approved these changes

2017-03-30 02:41 UTC, yongpingchen approved these changes

2017-03-30 03:37 UTC, shinsuke-nara commented
@naoki-akimoto 

aggregateの修正は今回はやめておきましょう。理由は以下の2つです。

1. 今回のPRの目的はgrouped用のqueryの実装なので、aggregateは関係がない
1. 修正した点は、複数のデータからHTTPリクエストを作る際にどのようにするべきかという問題で、これは他の箇所の実装方法にも影響を与える。どのような形が良いかは別途検討したい。

2017-03-30 03:38 UTC, dairyo requested changes

2017-03-30 03:38 UTC, shinsuke-nara commented on ThingIFSDK/ThingIFSDK/GroupedHistoryStatesQuery.swift
> +        json["firmwareVersion"] = self.firmwareVersion
jsonの中にaliasを入れていないようですが、これは不要？

2017-03-30 04:04 UTC, naoki-akimoto commented on ThingIFSDK/ThingIFSDK/GroupedHistoryStatesQuery.swift
> +        json["firmwareVersion"] = self.firmwareVersion
aliasはパス用のフィールドです。

2017-03-30 04:24 UTC, dairyo approved these changes

2017-03-30 04:26 UTC, shinsuke-nara commented
firmwareVersionの位置関係の問題があるということなので、この形を許容します。入力データからリクエストを作成する綺麗な方法については別途検討します。

2017-03-30 04:26 UTC, merged