add large tests for ThingIFAPI.query(HisotryStatesQuery).
KiiPlatform/IoTCloud-iOSSDK pull request #430
Opened 2017-03-31 09:52 UTC by naoki-akimoto

ThingIFAPI.query(HisotryStatesQuery)用のラージテストを追加しました。レビューをお願いします。
内容はAndroid側と同じです。

2017-04-03 06:16 UTC, dairyo requested changes

2017-04-03 06:16 UTC, dairyo commented on ThingIFSDK/ThingIFSDKLargeTests/ThingIFAPIQueryUngroupedTests.swift
> +            XCTAssertEqual(4, results!.count)
ここは数のチェックではなく、内容のチェックにするべきですね。

2017-04-03 06:16 UTC, dairyo commented on ThingIFSDK/ThingIFSDKLargeTests/ThingIFAPIQueryUngroupedTests.swift
> +        let query1 = HistoryStatesQuery(
Android版に揃えて、それぞれのテスト内容のコメントを追加しておきましょう。

2017-04-03 06:16 UTC, shinsuke-nara commented on ThingIFSDK/ThingIFSDKLargeTests/ThingIFAPIQueryUngroupedTests.swift
> +        let query5 = HistoryStatesQuery(
Android側のテストは新しいfirmware versionを追加し、昔のfirmware versionでの取得をチェックしています。こちらはそうなっていないので、そろえてください。

2017-04-03 06:16 UTC, shinsuke-nara commented on ThingIFSDK/ThingIFSDKLargeTests/ThingIFAPIQueryUngroupedTests.swift
> +
ここにもAndroidと同様のコメントを入れておきましょう。

2017-04-04 05:02 UTC, naoki-akimoto commented
@shinsuke-nara fixed. Please confirm.

2017-04-04 05:24 UTC, dairyo approved these changes

2017-04-04 05:29 UTC, naoki-akimoto commented
@yongpingchen Please confirm.

2017-04-04 05:57 UTC, yongpingchen approved these changes

2017-04-04 05:57 UTC, merged