Large tests for schedule command trigger
KiiPlatform/IoTCloud-iOSSDK pull request #432
Opened 2017-04-04 10:09 UTC by shinsuke-nara

* Move PostNewTriggerForSchedulePredicateTests.swift to ThingIFAPIScheduleTriggerTests.swift
* Fix some bugs. I followed implementation of thing-if AndroidSDK for below fixes.
  * `Command.commandID` becomes optional.
  * `Command.commandState` becomes optional.
  * `Command.created` becomes optional.

Related PR: #296

2017-04-04 10:30 UTC, naoki-akimoto approved these changes

2017-04-05 02:30 UTC, yongpingchen approved these changes

2017-04-05 02:40 UTC, rizakii requested changes

2017-04-05 02:40 UTC, rizakii commented on ThingIFSDK/ThingIFSDK/Command.swift
> +            created = nil
remove this, its not needed.

2017-04-05 02:40 UTC, rizakii commented on ThingIFSDK/ThingIFSDKLargeTests/ThingIFAPIScheduleTriggerTests.swift
> +                guard let triggers = triggers else {
no need to use guard, use `XCTAssertNotNil`

2017-04-05 02:40 UTC, rizakii commented on ThingIFSDK/ThingIFSDKTests/CommandTests.swift
> +        XCTAssertEqual(nil, actual.commandState)
use assertNil

2017-04-05 02:40 UTC, rizakii commented on ThingIFSDK/ThingIFSDKTests/ThingIFAPIGetCommandTests.swift
> +        setting.api.getCommand(testCase.commandID!) { command, error -> Void in
remove `-> Void `

2017-04-05 03:22 UTC, shinsuke-nara commented on ThingIFSDK/ThingIFSDK/Command.swift
> +            created = nil
@rizakii 

This is required.
We must initialize `let` before using it. If we remove `else` statement, it cause build error.

2017-04-05 03:24 UTC, shinsuke-nara commented on ThingIFSDK/ThingIFSDKLargeTests/ThingIFAPIScheduleTriggerTests.swift
> +                guard let triggers = triggers else {
@rizakii 

I want to use `triggers` as non optional so I used `guard`. `XCTAssertNotNil` does not unwrap optional value.

2017-04-05 03:29 UTC, rizakii commented on ThingIFSDK/ThingIFSDKLargeTests/ThingIFAPIScheduleTriggerTests.swift
> +                guard let triggers = triggers else {
```swift
XCTAssertNotNil(triggers)
let triggers = triggers!
```
better than use `guard`

2017-04-05 03:43 UTC, rizakii approved these changes

2017-04-05 03:43 UTC, rizakii commented
LGTM

2017-04-05 03:44 UTC, merged