Large tests for command APIs
KiiPlatform/IoTCloud-iOSSDK pull request #436
Opened 2017-04-05 07:45 UTC by shinsuke-nara

I Implemented large tests for command APIs.

Related PR: #296

2017-04-05 08:04 UTC, naoki-akimoto approved these changes

2017-04-05 10:06 UTC, rizakii requested changes
ThingIFAPICommandTests is better to have many test methods rather than one long methods.

2017-04-05 10:06 UTC, rizakii commented on ThingIFSDK/ThingIFSDKLargeTests/ThingIFAPICommandTests.swift
> +                    XCTAssertEqual([], commands)
please add message, since the assertion is unclear.

2017-04-05 10:06 UTC, rizakii commented on ThingIFSDK/ThingIFSDKLargeTests/ThingIFAPICommandTests.swift
> +        XCTAssertNotNil(gotPaginationKey)
why the assertion is here?

2017-04-05 10:06 UTC, rizakii commented on ThingIFSDK/ThingIFSDKLargeTests/ThingIFAPICommandTests.swift
> +    func testSuccess() {
this methods is unclear, please separate into smaller scope.

2017-04-05 10:32 UTC, rizakii requested changes

2017-04-05 10:32 UTC, rizakii commented on ThingIFSDK/ThingIFSDKLargeTests/ThingIFAPICommandTests.swift
> +                    XCTAssertTrue(createdCommands.insert(command).inserted)
please add comments here

2017-04-05 10:40 UTC, shinsuke-nara commented
@rizakii Add comments to test code. Please confirm.

2017-04-06 02:27 UTC, rizakii approved these changes
LGTM

2017-04-06 02:41 UTC, merged